### PR TITLE
Add more Python examples

### PR DESCRIPTION
**Pull request by nvitucci**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-46.surge.sh

Updated pages:
- [Read nodes](https://neo4j-docs-spark-46.surge.sh/spark/5/read/labels)
- [Write nodes](https://neo4j-docs-spark-46.surge.sh/spark/5/write/labels)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-46.surge.sh

Updated pages:
- [Read nodes](https://neo4j-docs-spark-46.surge.sh/spark/5/read/labels)
- [Read relationships](https://neo4j-docs-spark-46.surge.sh/spark/5/read/relationship)
- [Write nodes](https://neo4j-docs-spark-46.surge.sh/spark/5/write/labels)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-46.surge.sh

Updated pages:
- [Read nodes](https://neo4j-docs-spark-46.surge.sh/spark/5/read/labels)
- [Read relationships](https://neo4j-docs-spark-46.surge.sh/spark/5/read/relationship)
- [Write nodes](https://neo4j-docs-spark-46.surge.sh/spark/5/write/labels)
- [Write relationships](https://neo4j-docs-spark-46.surge.sh/spark/5/write/relationship)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-46.surge.sh

Updated pages:
- [Read nodes](https://neo4j-docs-spark-46.surge.sh/spark/5/read/labels)
- [Read relationships](https://neo4j-docs-spark-46.surge.sh/spark/5/read/relationship)
- [Write nodes](https://neo4j-docs-spark-46.surge.sh/spark/5/write/labels)
- [Write relationships](https://neo4j-docs-spark-46.surge.sh/spark/5/write/relationship)

**Review by fbiville — APPROVED** [review]

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-46.surge.sh

Updated pages:
- [Read nodes](https://neo4j-docs-spark-46.surge.sh/spark/5/read/labels)
- [Read relationships](https://neo4j-docs-spark-46.surge.sh/spark/5/read/relationship)
- [Write nodes](https://neo4j-docs-spark-46.surge.sh/spark/5/write/labels)
- [Write relationships](https://neo4j-docs-spark-46.surge.sh/spark/5/write/relationship)

**Pull request merged**
