### PR TITLE
Update Databricks page with Delta tables

### PR DESCRIPTION
**Pull request by nvitucci**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-41.surge.sh

Updated pages:
- [Databricks quickstart](https://neo4j-docs-spark-41.surge.sh/spark/5/databricks)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-41.surge.sh

Updated pages:
- [Databricks quickstart](https://neo4j-docs-spark-41.surge.sh/spark/5/databricks)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-41.surge.sh

Updated pages:
- [Databricks quickstart](https://neo4j-docs-spark-41.surge.sh/spark/5/databricks)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-41.surge.sh

Updated pages:
- [Databricks quickstart](https://neo4j-docs-spark-41.surge.sh/spark/5/databricks)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-41.surge.sh

Updated pages:
- [Databricks quickstart](https://neo4j-docs-spark-41.surge.sh/spark/5/databricks)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-41.surge.sh

Updated pages:
- [Databricks quickstart](https://neo4j-docs-spark-41.surge.sh/spark/5/databricks)

**Review by fbiville — APPROVED** [review]

**Pull request merged**
